COLOR_FAMILIES = {'lightsalmon':['Light Salmon','Red'],
                    'salmon':['Salmon','Red'],
                    'darksalmon':['Dark Salmon', 'Red'],
                    'lightcoral':['Light Coral', 'Red'],
                    'indianred':['Indian Red', 'Red'],
                    'crimson':['Crimson', 'Red'],
                    'firebrick':['Fire Brick', 'Red'],
                    'red':['Red', 'Red'],
                    'darkred':['Dark Red', 'Red'],
                    'coral':['Coral', 'Orange'],
                    'tomato':['Tomato', 'Orange'],
                    'orangered':['Orange Red', 'Orange'],
                    'gold':['Gold', 'Orange'],
                    'orange':['Orange', 'Orange'],
                    'darkorange':['Dark Orange', 'Orange'],
                    'lightyellow':['Light Yellow', 'Yellow'],
                    'lemonchiffon':['Lemon Chiffon', 'Yellow'],
                    'lightgoldenrodyellow':['Light Goldenrod Yellow', 'Yellow'],
                    'papayawhip':['Papaya Whip', 'Yellow'],
                    'moccasin':['Moccasin', 'Yellow'],
                    'peachpuff':['Peach Puff', 'Yellow'],
                    'palegoldenrod':['Pale Goldenrod', 'Yellow'],
                    'khaki':['Khaki', 'Yellow'],
                    'darkkhaki':['Dark Khaki', 'Yellow'],
                    'yellow':['Yellow', 'Yellow'],
                    'lawngreen':['Lawn Green', 'Green'],
                    'chartreuse':['Chartreuse', 'Green'],
                    'limegreen':['Lime Green', 'Green'],
                    'lime':['Lime', 'Green'],
                    'forestgreen':['Forest Green', 'Green'],
                    'green':['Green', 'Green'],
                    'darkgreen':['Dark Green', 'Green'],
                    'greenyellow':['Green Yellow', 'Green'],
                    'yellowgreen':['Yellow Green', 'Green'],
                    'springgreen':['Spring Green', 'Green'],
                    'mediumspringgreen':['Medium Spring Green', 'Green'],
                    'lightgreen':['Light Green', 'Green'],
                    'palegreen':['Pale Green', 'Green'],
                    'darkseagreen':['Dark Sea Green', 'Green'],
                    'mediumseagreen':['Medium Sea Green', 'Green'],
                    'seagreen':['Sea Green', 'Green'],
                    'olive':['Olive', 'Green'],
                    'darkolivegreen':['Dark Olive Green', 'Green'],
                    'olivedrab':['Olive Drab', 'Green'],
                    'lightcyan':['Light Cyan', 'Cyan'],
                    'cyan':['Cyan', 'Cyan'],
                    'aqua':['Aqua', 'Cyan'],
                    'aquamarine':['Aquamarine', 'Cyan'],
                    'mediumaquamarine':['Medium Aquamarine', 'Cyan'],
                    'paleturquoise':['Pale Turquoise', 'Cyan'],
                    'turquoise':['Turquoise', 'Cyan'],
                    'mediumturquoise':['Medium Turquoise', 'Cyan'],
                    'darkturquoise':['Dark Turquoise', 'Cyan'],
                    'lightseagreen':['Light Sea Green', 'Cyan'],
                    'cadetblue':['Cadet Blue', 'Cyan'],
                    'darkcyan':['Dark Cyan', 'Cyan'],
                    'teal':['Teal', 'Cyan'],
                    'powderblue':['Powder Blue', 'Blue'],
                    'lightblue':['Light Blue', 'Blue'],
                    'lightskyblue':['Light Sky Blue', 'Blue'],
                    'skyblue':['Sky Blue', 'Blue'],
                    'deepskyblue':['Deep Sky Blue', 'Blue'],
                    'lightsteelblue':['Light Steel Blue', 'Blue'],
                    'dodgerblue':['Dodger Blue', 'Blue'],
                    'cornflowerblue':['Cornflower Blue', 'Blue'],
                    'steelblue':['Steel Blue', 'Blue'],
                    'royalblue':['Royal Blue', 'Blue'],
                    'blue':['Blue', 'Blue'],
                    'mediumblue':['Medium Blue', 'Blue'],
                    'darkblue':['Dark Blue', 'Blue'],
                    'navy':['Navy', 'Blue'],
                    'midnightblue':['Midnight Blue', 'Blue'],
                    'mediumslateblue':['Medium Slate Blue', 'Blue'],
                    'slateblue':['Salte Blue', 'Blue'],
                    'darkslateblue':['Dark Slate Blue', 'Blue'],
                    'lavender':['Lavender', 'Purple'],
                    'thistle':['Thistle', 'Purple'],
                    'plum':['Plum', 'Purple'],
                    'violet':['Violet', 'Purple'],
                    'orchid':['Orchid', 'Purple'],
                    'fuchsia':['Fucshia', 'Purple'],
                    'magenta':['Magenta', 'Purple'],
                    'mediumorchid':['Medium Orchid', 'Purple'],
                    'mediumpurple':['Medium Purple', 'Purple'],
                    'blueviolet':['Blue Violet', 'Purple'],
                    'darkviolet':['Dark Violet', 'Purple'],
                    'darkorchid':['Dark Orchid', 'Purple'],
                    'darkmagenta':['Dark Magenta', 'Purple'],
                    'purple':['Purple', 'Purple'],
                    'indigo':['Indigo', 'Purple'],
                    'pink':['Pink', 'Pink'],
                    'lightpink':['Light Pink', 'Pink'],
                    'hotpink':['Hot Pink', 'Pink'],
                    'deeppink':['Deep Pink', 'Pink'],
                    'palevioletred':['Pale Violet Red', 'Pink'],
                    'mediumvioletred':['Medium Violet Red', 'Pink'],
                    'white':['White', 'White'],
                    'snow':['Snow', 'White'],
                    'honeydew':['Honeydew', 'White'],
                    'mintcream':['Mint Cream', 'White'],
                    'azure':['Azure', 'White'],
                    'aliceblue':['Alice Blue', 'White'],
                    'ghostwhite':['Ghost White', 'White'],
                    'whitesmoke':['White Smoke', 'White'],
                    'seashell':['Seashell', 'White'],
                    'beige':['Beige', 'White'],
                    'oldlace':['Old Lace', 'White'],
                    'floralwhite':['Floral White', 'White'],
                    'ivory':['Ivory', 'White'],
                    'antiquewhite':['Antique White', 'White'],
                    'linen':['Linen', 'White'],
                    'lavenderblush':['Lavender Blush', 'White'],
                    'mistyrose':['Misty Rose', 'White'],
                    'gainsboro':['Gainsboro', 'Gray'],
                    'lightgray':['Light Gray', 'Gray'],
                    'silver':['Silver', 'Gray'],
                    'darkgray':['Dark Gray', 'Gray'],
                    'gray':['Gray', 'Gray'],
                    'dimgray':['Dim Gray', 'Gray'],
                    'lightslategray':['Light Slate Gray', 'Gray'],
                    'slategray':['Slate Gray', 'Gray'],
                    'darkslategray':['Dark Slate Gray', 'Gray'],
                    'black':['Black', 'Black'],
                    'cornsilk':['Corn Silk', 'Brown'],
                    'blanchedalmond':['Blanched Almond', 'Brown'],
                    'bisque':['Bisque', 'Brown'],
                    'navajowhite':['Navajo White', 'Brown'],
                    'wheat':['Wheat', 'Brown'],
                    'burlywood':['Burly Wood', 'Brown'],
                    'tan':['Tan', 'Brown'],
                    'rosybrown':['Rosy Brown', 'Brown'],
                    'sandybrown':['Sandy Brown', 'Brown'],
                    'goldenrod':['Goldenrod', 'Brown'],
                    'peru':['Peru', 'Brown'],
                    'chocolate':['Chocolate', 'Brown'],
                    'saddlebrown':['Saddle Brown', 'Brown'],
                    'sienna':['Sienna', 'Brown'],
                    'brown':['Brown', 'Brown'],
                    'maroon':['Maroon', 'Brown']}